name: Build and Cache Go Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      # Step 3: Cache Go modules and build cache
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Step 4: Build the Go project
      - name: Build Go project
        run: |
          go mod tidy               # Ensure dependencies are up to date
          go build -o go-api        # Build the application with the module name `go-api`

      # Step 5: Upload the build artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: go-api-binary
          path: go-api               # Path to the binary

      # Step 6: (Optional) Save coverage reports (if you generate one)
      - name: Upload coverage report artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.out        # Specify the path if you have a coverage report file