name: Test Minikube Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up kubectl for Minikube
      - name: Set up kubectl for Minikube
        run: |
          # Ensure kubectl is using the Minikube context
          kubectl config use-context minikube
          # Verify the Minikube status
          kubectl get nodes

      # Step 3: Apply a simple Kubernetes manifest (Pod)
      - name: Deploy Test Pod
        run: |
          # Create a simple pod deployment YAML on the fly
          echo "
          apiVersion: v1
          kind: Pod
          metadata:
            name: test-pod
          spec:
            containers:
            - name: nginx
              image: nginx:latest
              ports:
              - containerPort: 80
          " | kubectl apply -f -

      # Step 4: Verify Pod Deployment
      - name: Verify Pod is Running
        run: |
          kubectl get pods
